// Mobile (iPhone landscape, touch): tooltip + Tap USE, merchants, shop + smith UIs are touch friendly, screenshots.
const puppeteer = require('puppeteer-core');
const URL = process.argv[2] || 'http://localhost:3010/';
const OUT = '/tmp/embertest/shots_v4';
const sleep = ms => new Promise(r => setTimeout(r, ms));
let fails = 0, passes = 0;
const ok = (c, msg) => { if (c) { passes++; console.log('  ok  ', msg); } else { fails++; console.log('  FAIL', msg); } };
(async () => {
  require('fs').mkdirSync(OUT, { recursive: true });
  const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
  const page = await browser.newPage();
  await page.emulate({ viewport: { width: 844, height: 390, deviceScaleFactor: 2, isMobile: true, hasTouch: true, isLandscape: true }, userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1' });
  const errs = [];
  page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') errs.push(m.type() + ': ' + m.text()); });
  page.on('pageerror', e => errs.push('pageerror: ' + e.message));
  await page.goto(URL, { waitUntil: 'networkidle0' });
  await page.evaluate(() => localStorage.removeItem('ember_meta')); await page.reload({ waitUntil: 'networkidle0' });
  const ev = (f, ...a) => page.evaluate(f, ...a);
  const tapSel = async (sel) => { await ev((s) => document.querySelector(s).scrollIntoView({ block: 'nearest', inline: 'nearest' }), sel); await sleep(600); const b = await (await page.$(sel)).boundingBox(); await page.touchscreen.tap(b.x + b.width / 2, b.y + b.height / 2); await sleep(250); };
  const txt = (sel) => ev((s) => (document.querySelector(s) || {}).innerText || '', sel);
  await page.tap('#soloBtn'); await sleep(1000);
  await ev(() => { __dbg.G.paused = false; document.getElementById('pause').classList.add('hidden'); });
  ok(await ev(() => document.body.classList.contains('touch')), 'touch layout active');
  // tooltip far vs near on touch
  await ev(() => { const { G } = __dbg; const s = G.level.rooms[0]; for (const p of [...G.pickups.values()]) if (p.kind === 'gun' || p.kind === 'hp') { G.host.pickups.delete(p.id); G.net.broadcast({ t: 'pk-', id: p.id, by: 0, pk: p }); } G.host.addPickup({ kind: 'gun', x: s.cx - 6, z: s.cz + 6, gun: { type: 'minigun', rarity: 2, affixes: ['static', 'brutal'] } }); window.__T = { x: s.cx - 6, z: s.cz + 6 }; });
  const stand = (d) => ev((d) => { const { me } = __dbg; me.x = __T.x + d; me.z = __T.z; me.yaw = Math.PI / 2; me.pitch = Math.atan2(-0.6, d); }, d);
  await stand(5.5); await sleep(500);
  const far = await ev(() => ({ card: !document.getElementById('gunCard').classList.contains('hidden'), use: getComputedStyle(document.getElementById('btnUse')).display }));
  await page.screenshot({ path: `${OUT}/tooltip_far_mobile.png` });
  await stand(2.2); await sleep(500);
  const near = await ev(() => ({ card: !document.getElementById('gunCard').classList.contains('hidden'), txt: document.getElementById('gunCard').innerText, use: getComputedStyle(document.getElementById('btnUse')).display }));
  await page.screenshot({ path: `${OUT}/tooltip_near_mobile.png` });
  ok(!far.card && far.use === 'none', 'mobile: 5.5m away no card and no USE button');
  ok(near.card && /Tap USE/.test(near.txt) && near.use !== 'none', 'mobile: 2.2m away card says "Tap USE" and the USE button is visible');
  await tapSel('#btnUse'); await sleep(400);
  ok(await ev(() => __me.guns.some(g => g.type === 'minigun')), 'mobile: Tap USE takes the weapon');
  // shop room
  await ev(() => { const { G, me } = __dbg; const sr = G.level.rooms.find(r => r.type === 'shop'); me.x = sr.entryPt[0]; me.z = sr.entryPt[1]; me.yaw = Math.atan2(-(sr.cx - me.x), -(sr.cz - 1 - me.z)); me.pitch = -0.1; __me.gold = 777; });
  await sleep(1200); await page.screenshot({ path: `${OUT}/merchants_in_room_mobile.png` });
  const standNpc = (kind) => ev((kind) => { const { G, me } = __dbg; const n = G.npcs.find(x => x.kind === kind); const ep = G.level.rooms[n.room].entryPt; const a = Math.atan2(ep[0] - n.x, ep[1] - n.z); me.x = n.x + Math.sin(a) * 3.0; me.z = n.z + Math.cos(a) * 3.0; me.yaw = Math.atan2(-(n.x - me.x), -(n.z - me.z)); me.pitch = -0.05; }, kind);
  await standNpc('shop'); await sleep(500);
  ok(await ev(() => getComputedStyle(document.getElementById('btnUse')).display !== 'none') && /Tap USE/.test(await txt('#prompt')), 'mobile: near the merchant the USE button + "Tap USE" prompt show');
  await page.screenshot({ path: `${OUT}/merchant_prompt_mobile.png` });
  await tapSel('#btnUse'); await sleep(500);
  ok(await ev(() => __dbg.G.merchantOpen), 'mobile: USE opens the shop');
  await page.screenshot({ path: `${OUT}/shop_mobile.png` });
  const fit = await ev(() => { const p = document.querySelector('.mpanel').getBoundingClientRect(); const c = document.getElementById('mClose').getBoundingClientRect(); return { w: p.width, h: p.height, vw: innerWidth, vh: innerHeight, closeH: c.height, closeTop: c.top }; });
  ok(fit.w <= fit.vw + 1 && fit.h <= fit.vh + 1 && fit.closeH >= 34 && fit.closeTop >= 0, 'mobile: panel fits the screen, Close button is large enough: ' + JSON.stringify(fit));
  const price = await ev(() => __me.shop.stock[0].price); const g0 = await ev(() => __me.gold);
  await tapSel('[data-buy="0"]');
  ok(await ev(() => !!document.querySelector('.mswap')), 'mobile: both slots full -> swap picker appears');
  await page.screenshot({ path: `${OUT}/shop_swap_mobile.png` });
  await tapSel('[data-swap="0"]');
  ok((await ev(() => __me.gold)) === g0 - price, 'mobile: tapping Buy purchases');
  await ev(() => { document.getElementById('mBody').scrollTop = 99999; }); await sleep(200);
  await page.screenshot({ path: `${OUT}/shop_mobile_bottom.png` });
  await ev(() => document.querySelector('[data-rrstock]').scrollIntoView({ inline: 'center', block: 'center' })); await sleep(1200); await tapSel('[data-rrstock]'); ok(await ev(() => __me.shop.n === 1), 'mobile: Reroll stock works by tap');
  await tapSel('#mClose'); ok(await ev(() => !__dbg.G.merchantOpen), 'mobile: Close button closes');
  // smith
  await standNpc('smith'); await sleep(400); await tapSel('#btnUse'); await sleep(500);
  ok(await ev(() => __dbg.G.merchantOpen && __dbg.shopState.kind === 'smith'), 'mobile: USE opens the smith');
  await ev(() => { __me.guns = []; __dbg.giveGun({ type: 'rifle', rarity: 0, affixes: [] }); __dbg.giveGun({ type: 'smg', rarity: 2, affixes: ['hair', 'keen'] }); __me.cur = 1; __me.gold = 900; const m = __dbg.meta; m.embers = 100; __dbg.setMeta(m); __dbg.openMerchant('smith'); });
  await ev(() => { __dbg.closeMerchant(); __dbg.openMerchant('smith'); }); await sleep(300);
  await tapSel('[data-sel="1"]');
  await page.screenshot({ path: `${OUT}/smith_mobile.png` });
  await tapSel('[data-reroll]');
  ok(await ev(() => !!__dbg.shopState.pending), 'mobile: Reroll by tap shows before/after');
  await ev(() => { document.getElementById('mBody').scrollTop = 0; }); await sleep(150);
  await page.screenshot({ path: `${OUT}/smith_mobile_reroll.png` });
  await tapSel('[data-keep]');
  await tapSel('[data-sel="0"]'); await tapSel('[data-up]');
  ok((await ev(() => __me.guns[0].rarity)) === 1 && JSON.parse(await ev(() => localStorage.getItem('ember_meta'))).embers === 60, 'mobile: Ember upgrade by tap (100 -> 60 saved)');
  await page.screenshot({ path: `${OUT}/smith_mobile_upgraded.png` });
  await tapSel('#mClose');
  console.log(errs.length ? 'CONSOLE ERRORS:\n' + errs.join('\n') : 'console: no errors/warnings');
  ok(errs.length === 0, 'no console errors');
  console.log(`shop_mobile.js: ${passes} passed, ${fails} failed`);
  await browser.close();
  process.exit(fails ? 1 : 0);
})().catch(e => { console.error('TEST FAIL', e); process.exit(1); });
